### ISSUE TITLE
GeoIP lookup is broken.

### ISSUE THREAD

**Issue by mikroskeem** [alphartdev/BungeeAdminTools#44]
```
16:32:07 [INFO] mikroskeem executed command: /bat lookup <scrubbed>
16:32:07 [SEVERE] [BungeeAdminTools] Error while fetching ip location from the API. Please report this :
java.lang.RuntimeException: java.net.ConnectException: Connection refused
    at fr.Alphart.BAT.Utils.Utils.getIpDetails(Utils.java:183)
    at fr.Alphart.BAT.Modules.Core.LookupFormatter.getSummaryLookupIP(LookupFormatter.java:262)
    at fr.Alphart.BAT.Modules.Core.CoreCommand$LookupCmd.onCommand(CoreCommand.java:259)
    at fr.Alphart.BAT.Modules.BATCommand$1.run(BATCommand.java:185)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
    at sun.net.www.http.HttpClient.New(HttpClient.java:308)
    at sun.net.www.http.HttpClient.New(HttpClient.java:326)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
    at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:989)
    at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:987)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:986)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
    at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
    at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1433)
    at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1430)
    at fr.Alphart.BAT.Utils.Utils.getIpDetails(Utils.java:163)
    ... 7 more
```

Also it seems that http://freegeoip.net is down. Maybe you should consider switching GeoIP provider?

**Comment by alphartdev** [comment]
Yeah it's solely caused by freegeoip.
Seems like ip-api is far better

**Comment by mikroskeem** [comment]
I was thinking about using [MaxMind GeoIP2](http://maxmind.github.io/GeoIP2-java/) API at first place, but this works fine too.
