### ISSUE TITLE
Couldn't get password - Problem with numeric only password

### ISSUE THREAD

**Issue by ghost** [alphartdev/BungeeAdminTools#46]
```
00:06:18 [INFORMACIÓN] Enabled plugin Yamler version 2.4.0-SNAPSHOTb-16 by geNAZt
00:06:18 [GRAVE] net.cubespace.Yamler.Config.InvalidConfigurationException: Could not set field
00:06:18 [GRAVE]     at net.cubespace.Yamler.Config.YamlConfig.internalLoad(YamlConfig.java:187)
00:06:18 [GRAVE]     at net.cubespace.Yamler.Config.YamlConfig.load(YamlConfig.java:158)
00:06:18 [GRAVE]     at net.cubespace.Yamler.Config.YamlConfig.init(YamlConfig.java:130)
00:06:18 [GRAVE]     at fr.Alphart.BAT.Configuration.<init>(Configuration.java:21)
00:06:18 [GRAVE]     at fr.Alphart.BAT.BAT.onEnable(BAT.java:60)
00:06:18 [GRAVE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
00:06:18 [GRAVE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:256)
00:06:18 [GRAVE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
00:06:18 [GRAVE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
00:06:18 [GRAVE] Caused by: java.lang.IllegalArgumentException: Can not set java.lang.String field fr.Alphart.BAT.Configuration.mysql_password to java.lang.Integer
00:06:18 [GRAVE]     at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
00:06:18 [GRAVE]     at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
00:06:18 [GRAVE]     at sun.reflect.UnsafeObjectFieldAccessorImpl.set(Unknown Source)
00:06:18 [GRAVE]     at java.lang.reflect.Field.set(Unknown Source)
00:06:18 [GRAVE]     at net.cubespace.Yamler.Config.InternalConverter.fromConfig(InternalConverter.java:161)
00:06:18 [GRAVE]     at net.cubespace.Yamler.Config.YamlConfig.internalLoad(YamlConfig.java:185)
00:06:18 [GRAVE]     ... 8 more
00:06:18 [INFORMACIÓN] Enabled plugin BungeeAdminTools version 1.4.2-basics by Alphart
00:06:18 [INFORMACIÓN] Enabled plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:7d2c2ab:1119 by SpigotMC
00:06:18 [INFORMACIÓN] Enabled plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:7d2c2ab:1119 by SpigotMC
00:06:18 [INFORMACIÓN] Enabled plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:7d2c2ab:1119 by SpigotMC
00:06:18 [INFORMACIÓN] Enabled plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:7d2c2ab:1119 by SpigotMC
00:06:18 [INFORMACIÓN] Listening on /0.0.0.0:25565
00:06:19 [GRAVE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@55183b20, id=1, owner=fr.Alphart.BAT.BAT@815b41f, task=fr.Alphart.BAT.BAT$3@5542c4ed, delay=0, period=0, running=true) encountered an exception
com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization
    at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:580)
    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:150)
    at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
    at fr.Alphart.BAT.database.DataSourceHandler.<init>(DataSourceHandler.java:75)
    at fr.Alphart.BAT.BAT$3.run(BAT.java:168)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:870)
    at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1659)
    at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1206)
    at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2234)
    at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265)
    at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064)
    at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
    at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
    at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
    at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
    at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:495)
    at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:564)
    ... 8 more
```

**Comment by qlimax5000** [comment]
Could you verify your YAML either [here](http://www.yamllint.com/) or [here](https://yaml-online-parser.appspot.com/), please?    Also, is it possible that your password is all numbers?

**Comment by TiTo-418** [comment]
@qlimax5000 It's all numbers

**Comment by qlimax5000** [comment]
Ah. That's the problem. I'm 99% sure that if you put a letter in your password it'll work. This isn't ideal though, and I'll look into a fix when I have time. (Unless @alphartdev or someone else beats me to it)

**Comment by alphartdev** [comment]
Yes just try with quotes.

And finally make sure your credentials are correct and that remote connection are enabled in MySQL.

**Comment by TiTo-418** [comment]
I tried with quotes, and I have several plugins using the sql server with the same credentials

**Comment by qlimax5000** [comment]
It's a bug in Yamler I think. Since BAT is using it to grab the value of mysql_password Yamler sees that it's only numbers (an int) and returns that. Then when BAT tries to authenticate with the data it fails since HikariCP needs a String for the password field.

I have an idea for a fix, but I'm insanely busy right now so you'll have to either wait for me (or someone else) to make a fix, or change your password (if using quotes didn't work. Remember, try with both double " and single ' quotes).

**Comment by TiTo-418** [comment]
I'll use a real password now lol, just letting you guys know

**Comment by qlimax5000** [comment]
Haha yeah. I was gonna say, an all numeric password doesn't sound very secure :P
Thanks for reporting it. :)

**Comment by alphartdev** [comment]
So at the end did it work with quotes or only with an alphanumeric password?

**Comment by TiTo-418** [comment]
@alphartdev Only with alphanumeric passwords

**Comment by alphartdev** [comment]
Alright, the quotes have helped in the past but it seems like they're not enough.
Which Yamler version are you using please?

**Comment by TiTo-418** [comment]
@alphartdev 2.4.0 (https://www.spigotmc.org/resources/yamler.315/download?version=83687)

**Comment by alphartdev** [comment]
Thanks!
